/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Lenovo
 */
public class dash extends javax.swing.JFrame {
int xx, xy;
    /**
     * Creates new form dash
     */
    public dash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sugeng = new javax.swing.JLabel();
        sugeng1 = new javax.swing.JLabel();
        loho = new javax.swing.JLabel();
        log_dash = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelround1 = new desain.panelround();
        panelround2 = new desain.panelround();
        panelround3 = new desain.panelround();
        panelround4 = new desain.panelround();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sugeng.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        sugeng.setForeground(new java.awt.Color(167, 243, 202));
        sugeng.setText("Septya");
        jPanel2.add(sugeng, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, -1));

        sugeng1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        sugeng1.setForeground(new java.awt.Color(167, 243, 202));
        sugeng1.setText("Warung Makan");
        jPanel2.add(sugeng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        loho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iyaaa.png"))); // NOI18N
        jPanel2.add(loho, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 90, -1));

        log_dash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dash 2 w.png"))); // NOI18N
        jPanel2.add(log_dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 70, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(167, 243, 202));
        jLabel2.setText("                  LOGOUT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 180, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/men.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("                 DASHBOARD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/STOK lstkagi 1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(167, 243, 202));
        jLabel6.setText("                  MENU");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trns.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(167, 243, 202));
        jLabel8.setText("                  STOK ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regis 1 w.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(167, 243, 202));
        jLabel10.setText("                  TRANSAKSI ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(167, 243, 202));
        jLabel12.setText("                  LAPORAN");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 180, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(167, 243, 202));
        jLabel14.setText("                  REGISTRASI ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 50));

        panelround1.setBackground(new java.awt.Color(0, 23, 18));
        panelround1.setRoundBottomLeft(30);
        panelround1.setRoundBottomright(30);
        panelround1.setRoundTopLeft(30);
        panelround1.setRoundTopRight(30);

        javax.swing.GroupLayout panelround1Layout = new javax.swing.GroupLayout(panelround1);
        panelround1.setLayout(panelround1Layout);
        panelround1Layout.setHorizontalGroup(
            panelround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelround1Layout.setVerticalGroup(
            panelround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.add(panelround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 680, 300));

        panelround2.setBackground(new java.awt.Color(0, 23, 18));
        panelround2.setRoundBottomLeft(30);
        panelround2.setRoundBottomright(30);
        panelround2.setRoundTopLeft(30);
        panelround2.setRoundTopRight(30);

        javax.swing.GroupLayout panelround2Layout = new javax.swing.GroupLayout(panelround2);
        panelround2.setLayout(panelround2Layout);
        panelround2Layout.setHorizontalGroup(
            panelround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        panelround2Layout.setVerticalGroup(
            panelround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.add(panelround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 200));

        panelround3.setBackground(new java.awt.Color(0, 23, 18));
        panelround3.setRoundBottomLeft(30);
        panelround3.setRoundBottomright(30);
        panelround3.setRoundTopLeft(30);
        panelround3.setRoundTopRight(30);

        javax.swing.GroupLayout panelround3Layout = new javax.swing.GroupLayout(panelround3);
        panelround3.setLayout(panelround3Layout);
        panelround3Layout.setHorizontalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        panelround3Layout.setVerticalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.add(panelround3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 190, 200));

        panelround4.setBackground(new java.awt.Color(0, 23, 18));
        panelround4.setRoundBottomLeft(30);
        panelround4.setRoundBottomright(30);
        panelround4.setRoundTopLeft(30);
        panelround4.setRoundTopRight(30);

        javax.swing.GroupLayout panelround4Layout = new javax.swing.GroupLayout(panelround4);
        panelround4.setLayout(panelround4Layout);
        panelround4Layout.setHorizontalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        panelround4Layout.setVerticalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.add(panelround4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 260, 200));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apal.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame 2.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
     xx = evt.getX();
     xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
      int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
    dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel log_dash;
    private javax.swing.JLabel loho;
    private desain.panelround panelround1;
    private desain.panelround panelround2;
    private desain.panelround panelround3;
    private desain.panelround panelround4;
    private javax.swing.JLabel sugeng;
    private javax.swing.JLabel sugeng1;
    // End of variables declaration//GEN-END:variables
}
