/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;



/**
 * * @author Lenovo
 */
public class login extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    private JButton bt_login;

    koneksi k = new koneksi();
    
    int xx, xy;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        k.connect();
    }
    
    class user {
       int id_user, id_level;
       String username, password, nama_user;
       
       public user(){
           this.id_user = 0;
           this.username = t_username1.getText();
           this.password = t_password.getText();
           this.nama_user = " ";
           this.id_level = 0;
       }
    }
    
    void bersih(){
        t_password.setText("username");
        t_password.setText("password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        t_username1 = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(547, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 70, 40));

        t_password.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        t_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passwordKeyPressed(evt);
            }
        });
        jPanel1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 240, 30));

        jButton1.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, 30));

        t_username1.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        t_username1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_username1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_username1FocusLost(evt);
            }
        });
        t_username1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_username1KeyPressed(evt);
            }
        });
        jPanel1.add(t_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 240, 30));

        username.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(0, 23, 18));
        username.setText("password");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 80, 20));

        password.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(0, 23, 18));
        password.setText("username");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame 1 (5).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
     xx = evt.getX();
     xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void t_username1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_username1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_username1KeyPressed

    private void t_username1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_username1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_username1FocusLost

    private void t_username1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_username1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_username1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user u = new user();
        try{
            this.stat = k.connect().prepareStatement("select * from user where "
                + "username='"+u.username+"' and password='"+u.password+"';");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                u.id_level = rs.getInt("id_level");
            }
            if(u.id_level==0){
                JOptionPane.showMessageDialog(null, "AKUN TIDAK DITEMUKAN");

            }else{
                switch(u.id_level){
                    case 1:
                    dash das = new dash();
                    das.setVisible(true);
                    this.setVisible(false);
                    break;
                    case 2:
                    transaksi tran = new transaksi();
                    tran.setVisible(true);
                    this.setVisible(false);
                    break;
                    case 3:
                    stok st = new stok();
                    st.setVisible(true);
                    this.setVisible(false);
                    break;
                    case 4:
                    bahan_baku baku = new bahan_baku();
                    baku.setVisible(true);
                    this.setVisible(false);
                    break;
                }
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passwordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            bt_login.requestFocus();
        }
    }//GEN-LAST:event_t_passwordKeyPressed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
        String username=t_password.getText();
        if(username.equals("")||username.equals("username")){
            t_password.setText("username");
        }
    }//GEN-LAST:event_t_passwordFocusLost

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
        String username = t_password.getText();
        if(username.equals("username")){
            t_password.setText("");
        }
    }//GEN-LAST:event_t_passwordFocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JTextField t_password;
    private javax.swing.JTextField t_username1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

   

        
    }

