/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Lenovo
 */
public class regis extends javax.swing.JFrame {

    /**
     * Creates new form regis
     */
    public regis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iduser = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        namauser = new javax.swing.JLabel();
        idlevel = new javax.swing.JLabel();
        id_user = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        id_level = new javax.swing.JTextField();
        daftar = new javax.swing.JButton();
        EXIT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iduser.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        iduser.setForeground(new java.awt.Color(0, 51, 51));
        iduser.setText("ID USER");
        jPanel1.add(iduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 150, 140, 30));

        user.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        user.setForeground(new java.awt.Color(0, 51, 51));
        user.setText("USERNAME");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 190, 140, 30));

        pass.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 51, 51));
        pass.setText("PASSWORD");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 230, 140, 30));

        namauser.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        namauser.setForeground(new java.awt.Color(0, 51, 51));
        namauser.setText("NAMA USER");
        jPanel1.add(namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 270, 140, 30));

        idlevel.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        idlevel.setForeground(new java.awt.Color(0, 51, 51));
        idlevel.setText("ID LEVEL");
        jPanel1.add(idlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 310, 140, 30));

        id_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_userActionPerformed(evt);
            }
        });
        jPanel1.add(id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 180, 30));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 180, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 180, 30));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 180, 30));

        id_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_levelActionPerformed(evt);
            }
        });
        jPanel1.add(id_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 180, 30));

        daftar.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        daftar.setForeground(new java.awt.Color(0, 51, 51));
        daftar.setText("DAFTAR");
        jPanel1.add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, 30));

        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });
        jPanel1.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame 2 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_userActionPerformed

    private void id_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_levelActionPerformed

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        dispose();
    }//GEN-LAST:event_EXITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EXIT;
    private javax.swing.JButton daftar;
    private javax.swing.JTextField id_level;
    private javax.swing.JTextField id_user;
    private javax.swing.JLabel idlevel;
    private javax.swing.JLabel iduser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel namauser;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField password;
    private javax.swing.JLabel user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
